name: telly_tracker
description: A package for tracking events in the Tellycom mobile app.
version: 1.0.0
homepage: https://github.com/mlab817/telly_tracker
repository: https://github.com/mlab817/telly_tracker
publish_to: 'https://pub.dev'

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  matomo_tracker: ^6.1.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
